//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Script
    {
        public string ClientName { get; set; }
        public string Field { get; set; }
        public string Text { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
